"""Amplifier module: session:start hook that injects a project memory briefing into context."""

import logging
from typing import Any

from project_memory_core import MemoryStore, resolve_db_path

logger = logging.getLogger(__name__)


async def mount(
    coordinator: Any,
    config: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Register a session:start handler that injects a project memory briefing.

    The briefing is generated by the Librarian agent and injected as ephemeral
    context so it appears at the top of the session without accumulating across
    turns.  If the DB does not exist or is empty the hook skips silently.
    """
    config = config or {}
    token_budget: int = config.get("token_budget", 1500)
    ephemeral: bool = config.get("ephemeral", True)

    async def on_session_start(event: Any) -> None:  # noqa: ARG001
        """Generate and inject a memory briefing at session start."""
        db_path = resolve_db_path(coordinator)

        if not db_path.exists():
            logger.debug(
                "hooks-session-briefing: no DB at %s — skipping briefing", db_path
            )
            return

        store = MemoryStore(db_path)
        try:
            stats = store.get_stats()
            if stats["total_memories"] == 0:
                logger.debug(
                    "hooks-session-briefing: DB has no curated memories — skipping briefing"
                )
                return

            briefing = await coordinator.delegate(
                agent="project-memory:librarian",
                task=(
                    f"Generate a session briefing within {token_budget} tokens. "
                    f"The project has {stats['total_memories']} memories across categories: "
                    f"{stats['by_category']}."
                ),
            )

            if briefing:
                await coordinator.inject_context(briefing, ephemeral=ephemeral)
                logger.info(
                    "hooks-session-briefing: injected briefing (%d memories)",
                    stats["total_memories"],
                )
            else:
                logger.debug("hooks-session-briefing: Librarian returned empty briefing")

        finally:
            store.close()

    coordinator.on("session:start", on_session_start)

    logger.info("hooks-session-briefing mounted: listening on session:start")

    return {
        "name": "hooks-session-briefing",
        "version": "0.1.0",
        "events": ["session:start"],
    }
